// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "./clientProviders/ClientProviders";


export const metadata: Metadata = {
  title: "MEF-Global Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
